# Generated by Django 5.2 on 2025-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='articulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fuente',
            field=models.CharField(default='compra', max_length=50),
        ),
    ]
