# Generated by Django 5.2 on 2025-06-11 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0002_alter_gasto_articulo_alter_gasto_fuente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=200)),
                ('mes', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuente', models.CharField(default='compra', max_length=50)),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], default='compra', max_length=10)),
                ('cuenta', models.CharField(blank=True, default='', max_length=200)),
                ('tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.tipogasto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumen.unidadnegocio')),
            ],
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
    ]
