# Generated by Django 5.2.3 on 2025-06-16 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0003_transaccion_delete_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='fuente',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='unidad',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='suma_todas_lasunidades',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='suma_unidad1',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipo_costo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='unidad1_1',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='unidad1_2',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='unidad1_3',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='unidad1_4',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='unidad1_5',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='unidad2',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='unidad3',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='unidad4',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='unidad5',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='unidad6',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='unidad7',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='unidad8',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cuenta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='mes',
            field=models.CharField(max_length=20),
        ),
    ]
