# Generated by Django 5.2.3 on 2025-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0004_remove_transaccion_articulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo_costo',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
